'use client'

import { Suspense, useEffect, useState } from "react"
import { Loader } from "./components/loader/Loader"


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  const [isLoading, setIsLoading] = useState(false)


  useEffect(() => {
    const hasSiteLoadedBefore = localStorage.getItem("Welcome");

    if (!hasSiteLoadedBefore) {
      localStorage.setItem("Welcome", "true");
      setIsLoading(true);
    }

    const timeout = setTimeout(() => {
      setIsLoading(false);
    }, 5000);

    return () => {
      clearTimeout(timeout);
    };
  }, [])

  return (

    <html lang="ru">
      <head>
        <title>Sierra</title>
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
        <link rel="icon" sizes="16x16" href="/favicon/favicon-16x16.png" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#262a2b" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="theme-color" content="#3c2f2f"></meta>
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </head>
      <body>
        <div className="container">
          {
            isLoading ? <div className="welcome">
              <div className="loader__black">
                <div className="home__page__load">
                  <Loader />
                </div>

              </div>
            </div>
              :
              <div className="home__page">
                <Suspense fallback={<div>Loading..</div>}>
                  {children}
                </Suspense>

              </div>
          }
        </div>
      </body>
    </html>
  )
}
